allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                if (compileSdkVersion instanceof String && compileSdkVersion.startsWith("android-")) {
                    compileSdkVersion 34
                } else if (compileSdkVersion instanceof Integer && compileSdkVersion > 34) {
                    compileSdkVersion 34
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
