allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

gradle.beforeProject { project ->
    if (project != rootProject) {
        project.plugins.withId("com.android.library") {
            if (project.hasProperty("android")) {
                project.android {
                    compileSdkVersion 34
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
